[project]
site_name = "Rabz JLB Site"
docs_dir = "docs"
extra_css = ["stylesheets/extra.css"]

# Navigation mapping (optional, or let Zensical auto-discover)
nav = [
    { "Home" = "index.md" },
    { "Infrastructure" = [
        "infrastructure/design.md",
        "infrastructure/cluster.md",
        "infrastructure/networking.md"
    ]},
    { "Services" = [
        "services/info.md",
        "services/tailscale.md",
        "services/duckdns.md",
        "services/adguard.md",
        "services/minecraft.md"
    ]}
]


[project.theme]
variant = "modern"
logo = "assets/logo.png"
favicon = "assets/favicon.png"
font.text = "Inter"
font.code = "Hack"
language = "en"
features = [
    "navigation.path"
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"
primary = "custom"
accent = "custom"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "custom"
accent = "custom"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
primary = "custom"
accent = "custom"